### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by arcanoroma** [RedToor/Katana#2]
When install Katana in my kali linux the installation show this:
root@kali:~/Desktop/inst/katana# ./install.py 
from: can't read /var/mail/core.Setting
from: can't read /var/mail/core
from: can't read /var/mail/core
from: can't read /var/mail/core
Error: no such file ""
Error: no such file ",+colors.W+                   \011\011\011\011 #' (No such file or directory)::                    +colors.B+,:+colors.W+       +colors.B+:,+colors.W+                   				 #"
Error: no such file ":,:"
Error: no such file "::,"
Error: no such file "                   +colors.B+,/./+colors.W+ _8_  +colors.B+\.\                  				 #"
Error: no "print" mailcap rules found for type "inode/directory"
Error: no such file "_8_"
Error: no such file ". "
./install.py: line 17: syntax error near unexpected token `('
./install.py: line 17: `print "                   "+colors.B+",\ \\"+colors.W+"/"+colors.P+"("+colors.R+"O"+colors.P+")"+colors.W+"\\"+colors.B+"/ /                  				 "#                   \ \/( O )\/ /         

to fix this please insert into the first line of install.py
#!/usr/bin/env python

Best regards
Marco Mirandola

**Comment by RedToor** [comment]
Hi Marco Mirandola, i'll add it, Thanks for interesting in the project.

Regards,
Red.
